; vmctx.inc — MASM-compatible constants

OFFSET_RIP          EQU     0h
OFFSET_RSP          EQU     8h
OFFSET_RAX          EQU     10h
OFFSET_RBX          EQU     18h
OFFSET_RCX          EQU     20h
OFFSET_RDX          EQU     28h
OFFSET_RSI          EQU     30h
OFFSET_RDI          EQU     38h
OFFSET_RBP          EQU     40h
OFFSET_R8           EQU     48h
OFFSET_R9           EQU     50h
OFFSET_R10          EQU     58h
OFFSET_R11          EQU     60h
OFFSET_R12          EQU     68h
OFFSET_R13          EQU     70h
OFFSET_R14          EQU     78h
OFFSET_R15          EQU     80h
OFFSET_FLAGS        EQU     88h

OFFSET_HOST_CONTEXT EQU     16920
OFFSET_VM_CONTEXT   EQU     17064
