cmake -B build ^
  -DCAPSTONE_ARM_SUPPORT=0 ^
  -DCAPSTONE_AARCH64_SUPPORT=0 ^
  -DCAPSTONE_ALPHA_SUPPORT=0 ^
  -DCAPSTONE_ARC_SUPPORT=0 ^
  -DCAPSTONE_HPPA_SUPPORT=0 ^
  -DCAPSTONE_LOONGARCH_SUPPORT=0 ^
  -DCAPSTONE_M680X_SUPPORT=0 ^
  -DCAPSTONE_M68K_SUPPORT=0 ^
  -DCAPSTONE_MIPS_SUPPORT=0 ^
  -DCAPSTONE_MOS65XX_SUPPORT=0 ^
  -DCAPSTONE_PPC_SUPPORT=0 ^
  -DCAPSTONE_SPARC_SUPPORT=0 ^
  -DCAPSTONE_SYSTEMZ_SUPPORT=0 ^
  -DCAPSTONE_XCORE_SUPPORT=0 ^
  -DCAPSTONE_TRICORE_SUPPORT=0 ^
  -DCAPSTONE_X86_SUPPORT=0 ^
  -DCAPSTONE_TMS320C64X_SUPPORT=0 ^
  -DCAPSTONE_EVM_SUPPORT=0 ^
  -DCAPSTONE_WASM_SUPPORT=0 ^
  -DCAPSTONE_BPF_SUPPORT=0 ^
  -DCAPSTONE_RISCV_SUPPORT=1 ^
  -DCAPSTONE_BUILD_SHARED=1 ^
  -DCMAKE_BUILD_TYPE=Release

cmake --build build --config Release
